// Generated from: tests\features\connectivityToolMap.feature
import { test } from "../../../tests/support/fixtures.ts";

test.describe('Connectivity Tool Map Navigation', () => {

  test.beforeEach('Background: Filter map functionality test', async ({ Given, homePage }, testInfo) => { if (testInfo.error) return;
    await Given('I am on the home page & I navigate to the connectivity tool map', null, { homePage }); 
  });
  
  test('Filter map test to validate expected results for local authority , destination and mode of transport filters', { tag: ['@filrermap'] }, async ({ When, Then, connectivityToolPage, page }) => { 
    await When('I apply filters on the map & select local authority view "Birmingham" & select Score by destination "Leisure" & Score by mode of transport "Cycling"', null, { connectivityToolPage }); 
    await Then('I should see expected results based on the applied filters', null, { connectivityToolPage, page }); 
  });

  test('Verify connectivity score on map view for local authority "Birmingham"', { tag: ['@connectivityscore'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
    await When('I select local authority view "Birmingham" & select tile on the map', null, { connectivityToolPage, mapHelper }); 
    await Then('I should see the connectivity score displayed correctly on the map', null, { connectivityToolPage }); 
  });

  test('Verify local authority band displayed on the map for local authority "Birmingham"', { tag: ['@localauthorityband'] }, async ({ When, Then, connectivityToolPage, mapHelper, page }) => { 
    await When('I select local authority view "Birmingham" & enable show authority band checkbox', null, { connectivityToolPage, mapHelper }); 
    await Then('I should see the authority bands displayed correctly on the map', null, { connectivityToolPage, page }); 
  });

  test.describe('Verify map filtering options for authority destination & mode of transport', () => {

    test('Example #1', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Birmingham" & select Scorebydestination as "Leisure" & Scorebymodeoftransport as "Cycling"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Birmingham", "Leisure", "Cycling"', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Manchester" & select Scorebydestination as "Workplaces" & Scorebymodeoftransport as "Driving"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Manchester", "Workplaces", "Driving"', null, { connectivityToolPage }); 
    });

    test('Example #3', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Leeds" & select Scorebydestination as "Education" & Scorebymodeoftransport as "Walking"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Leeds", "Education", "Walking"', null, { connectivityToolPage }); 
    });

    test('Example #4', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Liverpool" & select Scorebydestination as "Health" & Scorebymodeoftransport as "Public transport"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Liverpool", "Health", "Public transport"', null, { connectivityToolPage }); 
    });

    test('Example #5', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Newcastle upon Tyne" & select Scorebydestination as "Shopping" & Scorebymodeoftransport as "Cycling"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Newcastle upon Tyne", "Shopping", "Cycling"', null, { connectivityToolPage }); 
    });

    test('Example #6', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage }) => { 
      await When('I select localauthorityview as "Sheffield" & select Scorebydestination as "Residential" & Scorebymodeoftransport as "Driving"', null, { connectivityToolPage }); 
      await Then('I should see the map updated with all selected filtering options "Sheffield", "Residential", "Driving"', null, { connectivityToolPage }); 
    });

  });

  test.describe('Verify Score and Band on map for different filtering options', () => {

    test('Example #1', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Birmingham" & select Score by destination "Leisure" & Score by mode of transport "Cycling"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the map updated with the selected filtering options "Birmingham", "Leisure", "Cycling","85","[B]"', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Manchester" & select Score by destination "Workplaces" & Score by mode of transport "Driving"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the map updated with the selected filtering options "Manchester", "Workplaces", "Driving","87","[J]"', null, { connectivityToolPage }); 
    });

    test('Example #3', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Leeds" & select Score by destination "Education" & Score by mode of transport "Walking"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the map updated with the selected filtering options "Leeds", "Education", "Walking","69","[A]"', null, { connectivityToolPage }); 
    });

    test('Example #4', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Liverpool" & select Score by destination "Health" & Score by mode of transport "Public transport"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the map updated with the selected filtering options "Liverpool", "Health", "Public transport","75","[F]"', null, { connectivityToolPage }); 
    });

  });

  test.describe('Verify canvas screenshot for different locations', () => {

    test('Example #1', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Birmingham" & select Score by destination "Leisure" & Score by mode of transport "Cycling"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see canvas screenshot updated with the selected filtering options "Birmingham", "Leisure", "Cycling","85","[B]"', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Manchester" & select Score by destination "Workplaces" & Score by mode of transport "Driving"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see canvas screenshot updated with the selected filtering options "Manchester", "Workplaces", "Driving","87","[J]"', null, { connectivityToolPage }); 
    });

    test('Example #3', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Lincolnshire" & select Score by destination "Shopping" & Score by mode of transport "Cycling"', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see canvas screenshot updated with the selected filtering options "Lincolnshire", "Shopping", "Cycling","22","[D]"', null, { connectivityToolPage }); 
    });

  });

  test.describe('Verify canvas screenshot for different Map Opacity settings', () => {

    test('Example #1', { tag: ['@settings_canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select location "Blackpool, Borough of Blackpool, England, United Kingdom",coordinates 811,233,tile on the map & select Map "0.05"', null, { connectivityToolPage, mapHelper }); 
      await Then('I capture a canvas screenshot of the map with the "0.05" percentage applied for "Blackpool, Borough of Blackpool, England, United Kingdom"', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@settings_canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select location "Blackpool, Borough of Blackpool, England, United Kingdom",coordinates 811,233,tile on the map & select Map "0.25"', null, { connectivityToolPage, mapHelper }); 
      await Then('I capture a canvas screenshot of the map with the "0.25" percentage applied for "Blackpool, Borough of Blackpool, England, United Kingdom"', null, { connectivityToolPage }); 
    });

    test('Example #3', { tag: ['@settings_canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select location "Blackpool, Borough of Blackpool, England, United Kingdom",coordinates 811,233,tile on the map & select Map "0.5"', null, { connectivityToolPage, mapHelper }); 
      await Then('I capture a canvas screenshot of the map with the "0.5" percentage applied for "Blackpool, Borough of Blackpool, England, United Kingdom"', null, { connectivityToolPage }); 
    });

    test('Example #4', { tag: ['@settings_canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select location "Blackpool, Borough of Blackpool, England, United Kingdom",coordinates 811,233,tile on the map & select Map "0.75"', null, { connectivityToolPage, mapHelper }); 
      await Then('I capture a canvas screenshot of the map with the "0.75" percentage applied for "Blackpool, Borough of Blackpool, England, United Kingdom"', null, { connectivityToolPage }); 
    });

    test('Example #5', { tag: ['@settings_canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select location "Blackpool, Borough of Blackpool, England, United Kingdom",coordinates 811,233,tile on the map & select Map "1"', null, { connectivityToolPage, mapHelper }); 
      await Then('I capture a canvas screenshot of the map with the "1" percentage applied for "Blackpool, Borough of Blackpool, England, United Kingdom"', null, { connectivityToolPage }); 
    });

  });

  test.describe('Verify canvas screenshot for different public transport stops', () => {

    test('Example #1', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "City of London",Score by destination "Education",Score by mode of transport "Walking",public transport "Bus / Coach Bus /"', null, { connectivityToolPage, mapHelper }); 
      await Then('capture a canvas screenshot of the map for "City of London" with all "Bus / Coach Bus /" stops', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "City of London",Score by destination "Health",Score by mode of transport "Driving",public transport "National Rail"', null, { connectivityToolPage, mapHelper }); 
      await Then('capture a canvas screenshot of the map for "City of London" with all "National Rail" stops', null, { connectivityToolPage }); 
    });

    test('Example #3', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "City of London",Score by destination "Workplaces",Score by mode of transport "Public transport",public transport "Tube / Metro / LR"', null, { connectivityToolPage, mapHelper }); 
      await Then('capture a canvas screenshot of the map for "City of London" with all "Tube / Metro / LR" stops', null, { connectivityToolPage }); 
    });

    test('Example #4', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "City of London",Score by destination "Shopping",Score by mode of transport "Driving",public transport "Ferry"', null, { connectivityToolPage, mapHelper }); 
      await Then('capture a canvas screenshot of the map for "City of London" with all "Ferry" stops', null, { connectivityToolPage }); 
    });

    test('Example #5', { tag: ['@canvasscreenshot', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I select local authority view "Blackpool",Score by destination "Leisure",Score by mode of transport "Driving",public transport "Tram Tram"', null, { connectivityToolPage, mapHelper }); 
      await Then('capture a canvas screenshot of the map for "Blackpool" with all "Tram Tram" stops', null, { connectivityToolPage }); 
    });

  });

  test.describe('Verify Score on map for different local authorities', () => {

    test('Example #1', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I search for location "Hounslow West, London Borough of Hounslow" and select coordinates 476,275 on the map & select tile on the map', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the connectivity score displayed correctly on the map for "Hounslow West, London Borough of Hounslow" as "86"', null, { connectivityToolPage }); 
    });

    test('Example #2', { tag: ['@filtermap', '@regression'] }, async ({ When, Then, connectivityToolPage, mapHelper }) => { 
      await When('I search for location "Leeds, England, United Kingdom" and select coordinates 301,278 on the map & select tile on the map', null, { connectivityToolPage, mapHelper }); 
      await Then('I should see the connectivity score displayed correctly on the map for "Leeds, England, United Kingdom" as "87"', null, { connectivityToolPage }); 
    });

  });

  test('Verify Map Tiler is redicrected to expected screen and navigate back to connectivity tool map page', { tag: ['@MapTiler', '@regression', '@smoke'] }, async ({ When, Then, connectivityToolPage, mapTilePage, page }) => { 
    await When('I click on Map Tiler link on the connectivity tool map page', null, { connectivityToolPage }); 
    await Then('I should be redirected to Map Tiler screen and navigate back to connectivity tool map page', null, { connectivityToolPage, mapTilePage, page }); 
  });

  test('Verify GOV.UK link is redirected to expected screen and navigate back to connectivity tool map page', { tag: ['@GOVUK', '@regression', '@smoke'] }, async ({ When, Then, connectivityToolPage, page }) => { 
    await When('I click on GOV.UK link on the connectivity tool map page', null, { connectivityToolPage }); 
    await Then('I should be redirected to GOV.UK screen and navigate back to connectivity tool map page', null, { connectivityToolPage, page }); 
  });

  test('Verify Open Street Map Contributors link is redirected to expected screen and navigate back to connectivity tool map page', { tag: ['@openStreetMapContributors', '@regression', '@smoke'] }, async ({ When, Then, connectivityToolPage, openStreetMapPage, page }) => { 
    await When('I click on Open Street Map Contributors link on the connectivity tool map page', null, { connectivityToolPage }); 
    await Then('I should be redirected to Open Street Map Contributors screen and navigate back to connectivity tool map page', null, { connectivityToolPage, openStreetMapPage, page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\connectivityToolMap.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":7,"tags":["@filrermap"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When I apply filters on the map & select local authority view \"Birmingham\" & select Score by destination \"Leisure\" & Score by mode of transport \"Cycling\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Birmingham\"","children":[{"start":58,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Leisure\"","children":[{"start":101,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":139,"value":"\"Cycling\"","children":[{"start":140,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then I should see expected results based on the applied filters","stepMatchArguments":[]}]},
  {"pwTestLine":15,"pickleLine":12,"tags":["@connectivityscore"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Birmingham\" & select tile on the map","stepMatchArguments":[{"group":{"start":30,"value":"\"Birmingham\"","children":[{"start":31,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I should see the connectivity score displayed correctly on the map","stepMatchArguments":[]}]},
  {"pwTestLine":20,"pickleLine":17,"tags":["@localauthorityband"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Birmingham\" & enable show authority band checkbox","stepMatchArguments":[{"group":{"start":30,"value":"\"Birmingham\"","children":[{"start":31,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then I should see the authority bands displayed correctly on the map","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":27,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Birmingham\" & select Scorebydestination as \"Leisure\" & Scorebymodeoftransport as \"Cycling\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Birmingham\"","children":[{"start":32,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"Leisure\"","children":[{"start":76,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":113,"value":"\"Cycling\"","children":[{"start":114,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Birmingham\", \"Leisure\", \"Cycling\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Birmingham\"","children":[{"start":66,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Leisure\"","children":[{"start":80,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"\"Cycling\"","children":[{"start":91,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":32,"pickleLine":28,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Manchester\" & select Scorebydestination as \"Workplaces\" & Scorebymodeoftransport as \"Driving\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Manchester\"","children":[{"start":32,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"Workplaces\"","children":[{"start":76,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":116,"value":"\"Driving\"","children":[{"start":117,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Manchester\", \"Workplaces\", \"Driving\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Manchester\"","children":[{"start":66,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Workplaces\"","children":[{"start":80,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":93,"value":"\"Driving\"","children":[{"start":94,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":37,"pickleLine":29,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Leeds\" & select Scorebydestination as \"Education\" & Scorebymodeoftransport as \"Walking\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Leeds\"","children":[{"start":32,"value":"Leeds","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":70,"value":"\"Education\"","children":[{"start":71,"value":"Education","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":110,"value":"\"Walking\"","children":[{"start":111,"value":"Walking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Leeds\", \"Education\", \"Walking\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Leeds\"","children":[{"start":66,"value":"Leeds","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":74,"value":"\"Education\"","children":[{"start":75,"value":"Education","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":87,"value":"\"Walking\"","children":[{"start":88,"value":"Walking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":42,"pickleLine":30,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Liverpool\" & select Scorebydestination as \"Health\" & Scorebymodeoftransport as \"Public transport\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Liverpool\"","children":[{"start":32,"value":"Liverpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":74,"value":"\"Health\"","children":[{"start":75,"value":"Health","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":111,"value":"\"Public transport\"","children":[{"start":112,"value":"Public transport","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Liverpool\", \"Health\", \"Public transport\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Liverpool\"","children":[{"start":66,"value":"Liverpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":78,"value":"\"Health\"","children":[{"start":79,"value":"Health","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":88,"value":"\"Public transport\"","children":[{"start":89,"value":"Public transport","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":47,"pickleLine":31,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Newcastle upon Tyne\" & select Scorebydestination as \"Shopping\" & Scorebymodeoftransport as \"Cycling\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Newcastle upon Tyne\"","children":[{"start":32,"value":"Newcastle upon Tyne","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":84,"value":"\"Shopping\"","children":[{"start":85,"value":"Shopping","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":123,"value":"\"Cycling\"","children":[{"start":124,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Newcastle upon Tyne\", \"Shopping\", \"Cycling\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Newcastle upon Tyne\"","children":[{"start":66,"value":"Newcastle upon Tyne","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":88,"value":"\"Shopping\"","children":[{"start":89,"value":"Shopping","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Cycling\"","children":[{"start":101,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":52,"pickleLine":32,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I select localauthorityview as \"Sheffield\" & select Scorebydestination as \"Residential\" & Scorebymodeoftransport as \"Driving\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Sheffield\"","children":[{"start":32,"value":"Sheffield","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":74,"value":"\"Residential\"","children":[{"start":75,"value":"Residential","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":116,"value":"\"Driving\"","children":[{"start":117,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with all selected filtering options \"Sheffield\", \"Residential\", \"Driving\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Sheffield\"","children":[{"start":66,"value":"Sheffield","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":78,"value":"\"Residential\"","children":[{"start":79,"value":"Residential","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":93,"value":"\"Driving\"","children":[{"start":94,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":61,"pickleLine":41,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Birmingham\" & select Score by destination \"Leisure\" & Score by mode of transport \"Cycling\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Birmingham\"","children":[{"start":31,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Leisure\"","children":[{"start":74,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":112,"value":"\"Cycling\"","children":[{"start":113,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with the selected filtering options \"Birmingham\", \"Leisure\", \"Cycling\",\"85\",\"[B]\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Birmingham\"","children":[{"start":66,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Leisure\"","children":[{"start":80,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"\"Cycling\"","children":[{"start":91,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"85\"","children":[{"start":101,"value":"85","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":105,"value":"\"[B]\"","children":[{"start":106,"value":"[B]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":66,"pickleLine":42,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Manchester\" & select Score by destination \"Workplaces\" & Score by mode of transport \"Driving\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Manchester\"","children":[{"start":31,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Workplaces\"","children":[{"start":74,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":115,"value":"\"Driving\"","children":[{"start":116,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with the selected filtering options \"Manchester\", \"Workplaces\", \"Driving\",\"87\",\"[J]\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Manchester\"","children":[{"start":66,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Workplaces\"","children":[{"start":80,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":93,"value":"\"Driving\"","children":[{"start":94,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":103,"value":"\"87\"","children":[{"start":104,"value":"87","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":108,"value":"\"[J]\"","children":[{"start":109,"value":"[J]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":71,"pickleLine":43,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Leeds\" & select Score by destination \"Education\" & Score by mode of transport \"Walking\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Leeds\"","children":[{"start":31,"value":"Leeds","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Education\"","children":[{"start":69,"value":"Education","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":109,"value":"\"Walking\"","children":[{"start":110,"value":"Walking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with the selected filtering options \"Leeds\", \"Education\", \"Walking\",\"69\",\"[A]\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Leeds\"","children":[{"start":66,"value":"Leeds","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":74,"value":"\"Education\"","children":[{"start":75,"value":"Education","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":87,"value":"\"Walking\"","children":[{"start":88,"value":"Walking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":97,"value":"\"69\"","children":[{"start":98,"value":"69","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":102,"value":"\"[A]\"","children":[{"start":103,"value":"[A]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":76,"pickleLine":44,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Liverpool\" & select Score by destination \"Health\" & Score by mode of transport \"Public transport\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Liverpool\"","children":[{"start":31,"value":"Liverpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"\"Health\"","children":[{"start":73,"value":"Health","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":110,"value":"\"Public transport\"","children":[{"start":111,"value":"Public transport","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then I should see the map updated with the selected filtering options \"Liverpool\", \"Health\", \"Public transport\",\"75\",\"[F]\"","stepMatchArguments":[{"group":{"start":65,"value":"\"Liverpool\"","children":[{"start":66,"value":"Liverpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":78,"value":"\"Health\"","children":[{"start":79,"value":"Health","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":88,"value":"\"Public transport\"","children":[{"start":89,"value":"Public transport","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":107,"value":"\"75\"","children":[{"start":108,"value":"75","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":112,"value":"\"[F]\"","children":[{"start":113,"value":"[F]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":85,"pickleLine":54,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Birmingham\" & select Score by destination \"Leisure\" & Score by mode of transport \"Cycling\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Birmingham\"","children":[{"start":31,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Leisure\"","children":[{"start":74,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":112,"value":"\"Cycling\"","children":[{"start":113,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then I should see canvas screenshot updated with the selected filtering options \"Birmingham\", \"Leisure\", \"Cycling\",\"85\",\"[B]\"","stepMatchArguments":[{"group":{"start":75,"value":"\"Birmingham\"","children":[{"start":76,"value":"Birmingham","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"\"Leisure\"","children":[{"start":90,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Cycling\"","children":[{"start":101,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":110,"value":"\"85\"","children":[{"start":111,"value":"85","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":115,"value":"\"[B]\"","children":[{"start":116,"value":"[B]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":90,"pickleLine":55,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Manchester\" & select Score by destination \"Workplaces\" & Score by mode of transport \"Driving\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Manchester\"","children":[{"start":31,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Workplaces\"","children":[{"start":74,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":115,"value":"\"Driving\"","children":[{"start":116,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then I should see canvas screenshot updated with the selected filtering options \"Manchester\", \"Workplaces\", \"Driving\",\"87\",\"[J]\"","stepMatchArguments":[{"group":{"start":75,"value":"\"Manchester\"","children":[{"start":76,"value":"Manchester","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"\"Workplaces\"","children":[{"start":90,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":103,"value":"\"Driving\"","children":[{"start":104,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":113,"value":"\"87\"","children":[{"start":114,"value":"87","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":118,"value":"\"[J]\"","children":[{"start":119,"value":"[J]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":95,"pickleLine":56,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Lincolnshire\" & select Score by destination \"Shopping\" & Score by mode of transport \"Cycling\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Lincolnshire\"","children":[{"start":31,"value":"Lincolnshire","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"Shopping\"","children":[{"start":76,"value":"Shopping","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":115,"value":"\"Cycling\"","children":[{"start":116,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then I should see canvas screenshot updated with the selected filtering options \"Lincolnshire\", \"Shopping\", \"Cycling\",\"22\",\"[D]\"","stepMatchArguments":[{"group":{"start":75,"value":"\"Lincolnshire\"","children":[{"start":76,"value":"Lincolnshire","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":91,"value":"\"Shopping\"","children":[{"start":92,"value":"Shopping","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":103,"value":"\"Cycling\"","children":[{"start":104,"value":"Cycling","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":113,"value":"\"22\"","children":[{"start":114,"value":"22","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":118,"value":"\"[D]\"","children":[{"start":119,"value":"[D]","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":104,"pickleLine":64,"tags":["@settings_canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I select location \"Blackpool, Borough of Blackpool, England, United Kingdom\",coordinates 811,233,tile on the map & select Map \"0.05\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":19,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"811","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"233","children":[]},"parameterTypeName":"int"},{"group":{"start":126,"value":"\"0.05\"","children":[{"start":127,"value":"0.05","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I capture a canvas screenshot of the map with the \"0.05\" percentage applied for \"Blackpool, Borough of Blackpool, England, United Kingdom\"","stepMatchArguments":[{"group":{"start":50,"value":"\"0.05\"","children":[{"start":51,"value":"0.05","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":80,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":81,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":109,"pickleLine":65,"tags":["@settings_canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I select location \"Blackpool, Borough of Blackpool, England, United Kingdom\",coordinates 811,233,tile on the map & select Map \"0.25\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":19,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"811","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"233","children":[]},"parameterTypeName":"int"},{"group":{"start":126,"value":"\"0.25\"","children":[{"start":127,"value":"0.25","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I capture a canvas screenshot of the map with the \"0.25\" percentage applied for \"Blackpool, Borough of Blackpool, England, United Kingdom\"","stepMatchArguments":[{"group":{"start":50,"value":"\"0.25\"","children":[{"start":51,"value":"0.25","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":80,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":81,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":114,"pickleLine":66,"tags":["@settings_canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":115,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I select location \"Blackpool, Borough of Blackpool, England, United Kingdom\",coordinates 811,233,tile on the map & select Map \"0.5\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":19,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"811","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"233","children":[]},"parameterTypeName":"int"},{"group":{"start":126,"value":"\"0.5\"","children":[{"start":127,"value":"0.5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":116,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I capture a canvas screenshot of the map with the \"0.5\" percentage applied for \"Blackpool, Borough of Blackpool, England, United Kingdom\"","stepMatchArguments":[{"group":{"start":50,"value":"\"0.5\"","children":[{"start":51,"value":"0.5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":80,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":119,"pickleLine":67,"tags":["@settings_canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I select location \"Blackpool, Borough of Blackpool, England, United Kingdom\",coordinates 811,233,tile on the map & select Map \"0.75\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":19,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"811","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"233","children":[]},"parameterTypeName":"int"},{"group":{"start":126,"value":"\"0.75\"","children":[{"start":127,"value":"0.75","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":121,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I capture a canvas screenshot of the map with the \"0.75\" percentage applied for \"Blackpool, Borough of Blackpool, England, United Kingdom\"","stepMatchArguments":[{"group":{"start":50,"value":"\"0.75\"","children":[{"start":51,"value":"0.75","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":80,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":81,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":124,"pickleLine":68,"tags":["@settings_canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I select location \"Blackpool, Borough of Blackpool, England, United Kingdom\",coordinates 811,233,tile on the map & select Map \"1\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":19,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"811","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"233","children":[]},"parameterTypeName":"int"},{"group":{"start":126,"value":"\"1\"","children":[{"start":127,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I capture a canvas screenshot of the map with the \"1\" percentage applied for \"Blackpool, Borough of Blackpool, England, United Kingdom\"","stepMatchArguments":[{"group":{"start":50,"value":"\"1\"","children":[{"start":51,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":77,"value":"\"Blackpool, Borough of Blackpool, England, United Kingdom\"","children":[{"start":78,"value":"Blackpool, Borough of Blackpool, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":133,"pickleLine":76,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":134,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I select local authority view \"City of London\",Score by destination \"Education\",Score by mode of transport \"Walking\",public transport \"Bus / Coach Bus /\"","stepMatchArguments":[{"group":{"start":30,"value":"\"City of London\"","children":[{"start":31,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Education\"","children":[{"start":69,"value":"Education","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":107,"value":"\"Walking\"","children":[{"start":108,"value":"Walking","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":134,"value":"\"Bus / Coach Bus /\"","children":[{"start":135,"value":"Bus / Coach Bus /","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":135,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then capture a canvas screenshot of the map for \"City of London\" with all \"Bus / Coach Bus /\" stops","stepMatchArguments":[{"group":{"start":43,"value":"\"City of London\"","children":[{"start":44,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"Bus / Coach Bus /\"","children":[{"start":70,"value":"Bus / Coach Bus /","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":138,"pickleLine":77,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I select local authority view \"City of London\",Score by destination \"Health\",Score by mode of transport \"Driving\",public transport \"National Rail\"","stepMatchArguments":[{"group":{"start":30,"value":"\"City of London\"","children":[{"start":31,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Health\"","children":[{"start":69,"value":"Health","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":104,"value":"\"Driving\"","children":[{"start":105,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":131,"value":"\"National Rail\"","children":[{"start":132,"value":"National Rail","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then capture a canvas screenshot of the map for \"City of London\" with all \"National Rail\" stops","stepMatchArguments":[{"group":{"start":43,"value":"\"City of London\"","children":[{"start":44,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"National Rail\"","children":[{"start":70,"value":"National Rail","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":143,"pickleLine":78,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I select local authority view \"City of London\",Score by destination \"Workplaces\",Score by mode of transport \"Public transport\",public transport \"Tube / Metro / LR\"","stepMatchArguments":[{"group":{"start":30,"value":"\"City of London\"","children":[{"start":31,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Workplaces\"","children":[{"start":69,"value":"Workplaces","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":108,"value":"\"Public transport\"","children":[{"start":109,"value":"Public transport","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":144,"value":"\"Tube / Metro / LR\"","children":[{"start":145,"value":"Tube / Metro / LR","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":145,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then capture a canvas screenshot of the map for \"City of London\" with all \"Tube / Metro / LR\" stops","stepMatchArguments":[{"group":{"start":43,"value":"\"City of London\"","children":[{"start":44,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"Tube / Metro / LR\"","children":[{"start":70,"value":"Tube / Metro / LR","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":148,"pickleLine":79,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":149,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I select local authority view \"City of London\",Score by destination \"Shopping\",Score by mode of transport \"Driving\",public transport \"Ferry\"","stepMatchArguments":[{"group":{"start":30,"value":"\"City of London\"","children":[{"start":31,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Shopping\"","children":[{"start":69,"value":"Shopping","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":106,"value":"\"Driving\"","children":[{"start":107,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":133,"value":"\"Ferry\"","children":[{"start":134,"value":"Ferry","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":150,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then capture a canvas screenshot of the map for \"City of London\" with all \"Ferry\" stops","stepMatchArguments":[{"group":{"start":43,"value":"\"City of London\"","children":[{"start":44,"value":"City of London","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"Ferry\"","children":[{"start":70,"value":"Ferry","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":153,"pickleLine":80,"tags":["@canvasscreenshot","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":154,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I select local authority view \"Blackpool\",Score by destination \"Leisure\",Score by mode of transport \"Driving\",public transport \"Tram Tram\"","stepMatchArguments":[{"group":{"start":30,"value":"\"Blackpool\"","children":[{"start":31,"value":"Blackpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"\"Leisure\"","children":[{"start":64,"value":"Leisure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Driving\"","children":[{"start":101,"value":"Driving","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":127,"value":"\"Tram Tram\"","children":[{"start":128,"value":"Tram Tram","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":155,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then capture a canvas screenshot of the map for \"Blackpool\" with all \"Tram Tram\" stops","stepMatchArguments":[{"group":{"start":43,"value":"\"Blackpool\"","children":[{"start":44,"value":"Blackpool","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":64,"value":"\"Tram Tram\"","children":[{"start":65,"value":"Tram Tram","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":162,"pickleLine":88,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":163,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When I search for location \"Hounslow West, London Borough of Hounslow\" and select coordinates 476,275 on the map & select tile on the map","stepMatchArguments":[{"group":{"start":22,"value":"\"Hounslow West, London Borough of Hounslow\"","children":[{"start":23,"value":"Hounslow West, London Borough of Hounslow","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"476","children":[]},"parameterTypeName":"int"},{"group":{"start":93,"value":"275","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":164,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then I should see the connectivity score displayed correctly on the map for \"Hounslow West, London Borough of Hounslow\" as \"86\"","stepMatchArguments":[{"group":{"start":71,"value":"\"Hounslow West, London Borough of Hounslow\"","children":[{"start":72,"value":"Hounslow West, London Borough of Hounslow","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":118,"value":"\"86\"","children":[{"start":119,"value":"86","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":167,"pickleLine":89,"tags":["@filtermap","@regression"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":168,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When I search for location \"Leeds, England, United Kingdom\" and select coordinates 301,278 on the map & select tile on the map","stepMatchArguments":[{"group":{"start":22,"value":"\"Leeds, England, United Kingdom\"","children":[{"start":23,"value":"Leeds, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":78,"value":"301","children":[]},"parameterTypeName":"int"},{"group":{"start":82,"value":"278","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":169,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then I should see the connectivity score displayed correctly on the map for \"Leeds, England, United Kingdom\" as \"87\"","stepMatchArguments":[{"group":{"start":71,"value":"\"Leeds, England, United Kingdom\"","children":[{"start":72,"value":"Leeds, England, United Kingdom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":107,"value":"\"87\"","children":[{"start":108,"value":"87","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":174,"pickleLine":92,"tags":["@MapTiler","@regression","@smoke"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":175,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When I click on Map Tiler link on the connectivity tool map page","stepMatchArguments":[]},{"pwStepLine":176,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then I should be redirected to Map Tiler screen and navigate back to connectivity tool map page","stepMatchArguments":[]}]},
  {"pwTestLine":179,"pickleLine":97,"tags":["@GOVUK","@regression","@smoke"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":180,"gherkinStepLine":98,"keywordType":"Action","textWithKeyword":"When I click on GOV.UK link on the connectivity tool map page","stepMatchArguments":[]},{"pwStepLine":181,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"Then I should be redirected to GOV.UK screen and navigate back to connectivity tool map page","stepMatchArguments":[]}]},
  {"pwTestLine":184,"pickleLine":102,"tags":["@openStreetMapContributors","@regression","@smoke"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am on the home page & I navigate to the connectivity tool map","isBg":true,"stepMatchArguments":[]},{"pwStepLine":185,"gherkinStepLine":103,"keywordType":"Action","textWithKeyword":"When I click on Open Street Map Contributors link on the connectivity tool map page","stepMatchArguments":[]},{"pwStepLine":186,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"Then I should be redirected to Open Street Map Contributors screen and navigate back to connectivity tool map page","stepMatchArguments":[]}]},
]; // bdd-data-end